//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment_manage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecivesInfo
    {
        public string di_EqId { get; set; }
        public string di_User { get; set; }
        public string di_Name { get; set; }
        public int dt_ID { get; set; }
        public string di_Model { get; set; }
        public double di_Price { get; set; }
        public string di_ManuFacturers { get; set; }
        public string di_Position { get; set; }
        public System.DateTime di_ButTime { get; set; }
        public System.DateTime di_Warranty { get; set; }
        public string di_Status { get; set; }

    }
}
