//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment_manage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int d_ID { get; set; }
        public string d_Name { get; set; }
        public Nullable<int> d_SortIndex { get; set; }
    }
}
