//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment_manage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int e_ID { get; set; }
        public string e_Name { get; set; }
        public string e_Gender { get; set; }
        public string e_Mobile { get; set; }
        public int d_ID { get; set; }
        public Nullable<int> e_SortIndex { get; set; }
        public int work_number;
        public void clone(Employees a)
        {
            this.e_ID = a.e_ID;
            this.e_Name = a.e_Name;
            this.e_Gender = a.e_Gender;
            this.e_Mobile = a.e_Mobile;
            this.d_ID = a.d_ID;
            this.e_SortIndex = a.e_SortIndex;
        }
    }
}
